{% set version = "0.4.1" %}
{% set commit = "46315431aeda3b6968b3ac4c1087f6d41052b99d" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: c784da3f900174ea36983a190f369acb408919ff710a95365222ef35bfa58d08

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy x.x
    - six
    - arrow-cpp 0.4.1
    - parquet-cpp 1.2.0.pre

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - six
    - arrow-cpp 0.4.1
    - parquet-cpp 1.2.0.pre

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow._jemalloc  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
