{% set version = "0.17.1" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "cbc51c343bca08b10f7f1b2ef15cb15057c30e5e9017cfcee18337b7e2da9ea2" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 1

requirements:
  build:
    - cmake 3.16.*
    - ninja
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - arrow-cpp {{ version }}
    - boost-cpp
    - cython
    - numpy 1.16.*
    - python
    - setuptools
    - setuptools_scm
    - six

  run:
    - {{ pin_compatible('numpy', lower_bound='1.16') }}
    - boost-cpp
    - futures  # [py==27]
    - glog
    - pandas
    # empty parquet-cpp metapackage, force old versions to be uninstalled
    - parquet-cpp 1.5.1.*
    - python
    - six
    - snappy

test:
  imports:
    - pyarrow
    - pyarrow.dataset  # [not py==27]
    - pyarrow.flight   # [not py==27]
    - pyarrow.gandiva  # [(not py==27) and (not (aarch64 or ppc64le))]
    - pyarrow.orc      # [unix]
    - pyarrow.parquet
    - pyarrow.plasma   # [unix]
    - pyarrow.fs
    - pyarrow._s3fs
    - pyarrow._hdfs

about:
  home: http://github.com/apache/arrow
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python libraries for Apache Arrow

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
