{% set version = "0.7.1" %}
{% set commit = "0e21f84c2fc26dba949a03ee7d7ebfade0a65b81" %}
{% set checksum = "39734331cc2eb71f764ea40b814cc67b24bcb6bb6db0bcc6eba22a49969577f9" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 1
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy 1.10.*  # [not (win and py>=36)]
    - numpy 1.12.*  # [win and py>=36]
    - six
    - arrow-cpp 0.7.1
    - parquet-cpp 1.3.*

  run:
    - python
    - setuptools
    - numpy >=1.10  # [not (win and py>=36)]
    - numpy >=1.12  # [win and py>=36]
    - pandas
    - six
    - arrow-cpp 0.7.1
    - parquet-cpp 1.3.*

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
