{% set version = "0.5.0.pre" %}
{% set commit = "b4d34f8fde52df14f087cedcca8b7276b5cf0697" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 0d3b9bfbfb4c4024542191694d8a469949ce02367e3034499a2d3c15e3f85c2f

build:
  number: 2
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy x.x
    - six
    - arrow-cpp 0.5.*
    - parquet-cpp 1.2.*

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - six
    - arrow-cpp 0.5.*
    - parquet-cpp 1.2.*

test:
  imports:
    - pyarrow
    - pyarrow.parquet

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
