{% set version = "0.4.0" %}
{% set commit = "a8f8ba0cbcf5f596f042e90b7a208e7a0c3925b7" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: d40ca0491918e7b74223068f47a4f475a7c489e0f001f04907b7e7c232a491c3

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy x.x
    - six
    - arrow-cpp 0.4.*
    - parquet-cpp 1.1.0

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - six
    - arrow-cpp 0.4.*
    - parquet-cpp 1.1.0

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow._jemalloc  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
