{% set version = "0.1.post" %}
{% set commit = "4226adfbc6b3dff10b3fe7a6691b30bcc94140bd" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 22bb4a1a3922827c267b113854d3c6d7bd8bb40e5ea117cb96df10eef74e7fde

build:
  number: 7
  rpaths:
    - lib  # [unix]
    - lib/python{{ environ['PY_VER'] }}/site-packages/pyarrow  # [unix]
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - arrow-cpp
    - cython
    - cmake
    - numpy x.x
    - six
    - parquet-cpp

  run:
    - python
    - setuptools
    - arrow-cpp
    - numpy x.x
    - pandas
    - parquet-cpp
    - six

test:
  imports:
    - pyarrow
    - pyarrow.io
    - pyarrow.ipc
    - pyarrow.parquet

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
