{% set version = "0.3.0.post" %}
{% set commit = "37dbddf0dc6582586a2bea98a436cb20726799a4" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 86b703ba6fb66a812b5eea99b4b6e7d655ad62969962c74ecc4087615e6e1c6f

build:
  number: 1
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy x.x
    - six
    - arrow-cpp 0.3.*
    - parquet-cpp 1.1.*  # [unix]

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - six
    - arrow-cpp 0.3.*
    - parquet-cpp 1.1.*  # [unix]

test:
  imports:
    - pyarrow
    - pyarrow._jemalloc  # [unix]
    - pyarrow.parquet    # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
