{% set version = "0.2.post" %}
{% set commit = "f6924ad83bc95741f003830892ad4815ca3b70fd" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: d78fcb18284ce043f3375096deaed83ff491c95237e9ba3ec5349a1c760fb14b

build:
  number: 0
  rpaths:
    - lib  # [unix]
    - lib/python{{ environ['PY_VER'] }}/site-packages/pyarrow  # [unix]
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - arrow-cpp 0.2.*
    - cython
    - cmake
    - numpy x.x
    - six
    - parquet-cpp

  run:
    - python
    - setuptools
    - arrow-cpp
    - numpy x.x
    - pandas
    - parquet-cpp
    - six

test:
  imports:
    - pyarrow
    - pyarrow.io
    - pyarrow.ipc
    - pyarrow.parquet

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
