{% set version = "0.10.0" %}
{% set commit = "07f142df646c9070fc9c627004dfdc96914fe487" %}
{% set checksum = "943207a2fcc7ba8de0e50bdb6c6ea4e9ed7f7e7bf55f6b426d7f867f559e842d" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools_scm
    - cython
    - numpy 1.10.*   # [not (win and py>=36)]
    - numpy 1.12.*   # [win and py>=36]
    - six
    - arrow-cpp 0.10.0
    - parquet-cpp 1.5.0.pre

  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy', lower_bound='1.10') }}   # [not (win and py>=36)]
    - {{ pin_compatible('numpy', lower_bound='1.12') }}   # [win and py>=36]
    - pandas
    - six
    - arrow-cpp 0.10.0
    - parquet-cpp 1.5.0.pre
    - futures  # [py27]

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
