{% set version = "0.1.post" %}
{% set commit = "79344b335849c2eb43954b0751018051814019d6" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 8712b2750556f1ca500ce9f7ea3e03715a2721e371aa1faf9a67db9862d88a73

build:
  number: 2
  rpaths:
    - lib  # [unix]
    - lib/python{{ environ['PY_VER'] }}/site-packages/pyarrow  # [unix]
  skip: true  # [not linux]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - arrow-cpp
    - cython
    - cmake
    - numpy x.x
    - six
    - parquet-cpp

  run:
    - python
    - arrow-cpp
    - numpy x.x
    - pandas
    - parquet-cpp
    - six

test:
  imports:
    - pyarrow
    - pyarrow.io
    - pyarrow.ipc
    - pyarrow.parquet

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
