{% set version = "0.8.0" %}
{% set commit = "1d689e5a3e417d3a4b3de16fea7a6fe195c8f8df" %}
{% set checksum = "abd102b9be07b22e629cd6918ffde5e36ed17a54c127d218f6b57ff0ffce1c64" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy 1.10.*  # [not (win and py>=36)]
    - numpy 1.12.*  # [win and py>=36]
    - six
    - arrow-cpp 0.8.0
    - parquet-cpp 1.4.*

  run:
    - python
    - setuptools
    - numpy >=1.10  # [not (win and py>=36)]
    - numpy >=1.12  # [win and py>=36]
    - pandas
    - six
    - arrow-cpp 0.8.0
    - parquet-cpp 1.4.*
    - futures  # [py27]

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
