{% set version = "0.3.0" %}
{% set commit = "d8db8f8a11abbbb6c45645b2d7370610311731bd" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: fc285c4a54c82e84bfbf0a66a8cef0c3c9dcae3f2c12e591e723bad6b75b5bef

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy x.x
    - six
    - arrow-cpp 0.3.*
    - parquet-cpp 1.1.*  # [unix]

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - six
    - arrow-cpp 0.3.*
    - parquet-cpp 1.1.*  # [unix]

test:
  imports:
    - pyarrow
    - pyarrow._jemalloc  # [unix]
    - pyarrow.parquet    # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
