{% set version = "0.12.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "34dae7e4dde9274e9a52610683e78a80f3ca312258ad9e9f2c0973cf44247a98" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - boost-cpp
    - python
    - setuptools
    - setuptools_scm
    - cython
    - numpy 1.14.*
    - six
    - arrow-cpp {{ version }}

  run:
    - boost-cpp
    - python
    - setuptools
    - {{ pin_compatible('numpy', lower_bound='1.14') }}
    - pandas
    - six
    - futures  # [py27]
    - arrow-cpp {{ version }}
    # empty parquet-cpp metapackage, force old versions to be uninstalled
    - parquet-cpp 1.5.1

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
