{% set version = "0.1.post" %}
{% set commit = "3195948f64770520c7ed4c8a7888b33402ad6519" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 2ca012ab8a2a441c4fb1ff33d416c9466d250285634f23dc291748caf4457726

build:
  number: 5
  rpaths:
    - lib  # [unix]
    - lib/python{{ environ['PY_VER'] }}/site-packages/pyarrow  # [unix]
  skip: true  # [not linux]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - arrow-cpp
    - cython
    - cmake
    - numpy x.x
    - six
    - parquet-cpp

  run:
    - python
    - setuptools
    - arrow-cpp
    - numpy x.x
    - pandas
    - parquet-cpp
    - six

test:
  imports:
    - pyarrow
    - pyarrow.io
    - pyarrow.ipc
    - pyarrow.parquet

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
