{% set version = "0.3.pre" %}
{% set commit = "928b63f40d4d8234644acca36d41bed9390f5f3a" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: 4ac93d4f4e890d109993665600bd1036f8ab495bedd8efcec9bde5b03bcdbcc3

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy x.x
    - six
    - arrow-cpp 0.3.*
    - parquet-cpp 1.1.*  # [unix]

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - six
    - arrow-cpp 0.3.*
    - parquet-cpp 1.1.*  # [unix]

test:
  imports:
    - pyarrow
    - pyarrow._jemalloc  # [unix]
    - pyarrow.parquet    # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
