appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: EiOFEzM1XtKqTQqSo+nnIzIaNJpZxWsI1GJ8unI+eD9V519APMGNcflft6G1zuO0GcUEnUJlqvURRi8QQHow1Ay6Nvrmwf+2CGUfgmqjtQDRo15ObwzTqDZxMFpMgUMIpuLRa5vIwYDW5/hNOcxgaIx6sqDVSa0EsZY0KFBbHkfaqiX2h6iSN3H3KOG9Y3tjRf00DBGZbbqY+uKszH9aX18f+uKKiNh2uLFfalcyePEmKInqqLFDtY4g0X+FOMYm31ZaHTJCgyPvnLhExw57WnuUs3Vvra+ibYZgjPmHB67xVIhqWe0VQPXCCAXAosDK16OTtzcQUe3Cycrp/K1cbjo4hcUQLQnzpgmNhIBuk6ttGSnyCeyr/otgqaF+Ah43FbJlqmq6hD75cdHNhbkvnde6Z2jpOHe2MOL4EvOb6qJn/YE6HN3zoYaKFzT6qqotQIoBf7oYi6VHAztO6kpwv6CAeVJnTtTj8YOOUyv6GWGXn1e4ehyhg9zkR5BPlvj05p+oaw2BcL3Qj7khZOog066NcxjBRlkZcfL9BXBPeCa2/k4RmzzNcdfCX/PdMY0JfzD03g6NGLCt0jJHhaXKS78WzwOjVVz00cz1jhCcPLTBQn9OqZHPmAxbE6BULuuFdlxnxdooQSJavVj5cdxR6oexSI+vEXjIEDcMEZgXph8=}
