travis:
  secure:
    BINSTAR_TOKEN: uClOicjDEjlClpGD/h/QGdwbPiAzb30aBqLMJfAM9V+aPirxyOl85cVbhUY9YuFkzT5AGftEgZFfww8fTrfgQ1yp96BJjnez2dgElhh1z2drte+qDJd9U259oxgzwGejc7iKivzH/pUOG2Z3o7+qcFFRh7TD9DUxrbHEXWDKReIRS25advaUZYD+SH91FSemWCi/7jJ49tFr93jJ0b2gUa5YD/0A4nLclzx5fUMVCLrRXEKiAxW6xyAP1Tu2CymHQ6/XZVxXzecT8sCfDIkf84yn7Oo54HxQS2c33CFDtV7H0CX72rPvix/cmc5fKO3kzjIP1pXfVUfJU8cFdfCLueB3JNfdI2YTrN5YRcFFfGFDdTHEP/VoG389bUC4dLdl5Wj53yqoFq/DCqMfu3M50ZDDjn0/2OdqpMOxMK4OMZPqW0iLm4E3j393p8/ZClbB2gXy/uqmlF64XR/PZrtmqkRIc/cHvleKb7eGugjcP7P36qYZpYCGSsMW7J/uA2d/3gtJZa1WesmeuO/Z+btHUfUwkpXYTVEHzFs8wgvFSw/pfrnduLmLOF1i3t6dUGTFMYJvtdWt2wrtpPTlx9bSN2KejdgCRa3cA+GnZi3JzdUPPdiOd8kbKRrwpsb4o6IxwVRxxe1tf5eRwzlcwJlH763i/DJYuam10z9pdSVgOk8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
